In [6]:
text =  ['This is very powerful, but is also very dangerous if you accept strings to evaluate from untrusted input. Suppose the string being evaluated is  It will really start deleting all the files on your computer',
        'Safely evaluate an expression node or a string containing a Python literal or container display. The string or node provided may only consist of the following Python literal structures: strings, bytes, numbers, tuples, lists, dicts, sets, booleans, None, bytes and sets.',
        'The string or node provided may only consist of the following Python literal structures: strings, bytes, numbers, tuples, lists, dicts, sets, booleans, and None',
        'means that you actually evaluate the code before you deem it to be unsafe or not. It evaluates the code as soon as the function is called.',
        'I read through the docs and I am still unclear if this would be safe or not. Does eval evaluate the data as soon as its entered or after the datamap variable is called?']

# **CountVectorizer**

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

In [8]:
# it creates a 'document-term matrix'
#columns represents the unique tokens and each row represents a document.
#Each cell represents frequency of each word corresponding to that document.
#like, w1 occured thrice, twice and once in doc d1,d2,d3 resp.

In [9]:
#      w1  w2 w3 ...             #w1,w2,w3 unique tokens throughout the documents
#   d1  2  0  1  ...             #d1,d2,d3 documents
#   d2  1  1  3  ...
#   d3  3  2  1  ...
#   .   .  .  .
#   .   .  .  .
#   .   .  .  .

In [10]:
cv = CountVectorizer()
x = cv.fit(text)

In [11]:
#x.vocabulary_     #vocab of unique words nd their corresponding indices

In [12]:
y = cv.transform(text)
#it transform the text documents to document-term- matrix

In [13]:
y.shape   #5 documents and 87 unique tokens

(5, 87)

In [14]:
y.toarray()

array([[1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 3, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
        1, 0, 1, 1, 0, 1, 0, 2, 1, 0, 1, 0, 0, 0, 1, 0, 2, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 2, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 2, 1, 0, 2, 1, 0, 1, 1, 0, 1, 3, 0, 1, 2, 0, 0, 0, 1, 2, 0,
        0, 0, 2, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 2, 1, 1, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 

# **TDIDF Vectorizer**

In [15]:
# it creates a 'document-term matrix'
# columns represents the unique tokens and each row represents a document.
# each cell contains a tf-idf weight which signifies how imp a word is for an individual document.

# TF-IDF = TF*IDF

#Term-Frequency: which measures how frequently a term occurs in a document. Since every document is different in length,
#it is possible that a term would appear much more times in long documents than shorter ones. thus term-freq is often
#divided by the document length as a way of normalization:

#TF(t,d) = (No of times term 't' appears in document(d))/(Total no terms in document(j)).

#Inverse Document Frequency: it measures how imp the term is. while computing TF, all terms are considered equally imp. However it is known 
#that certain terms, such as 'is','of','that', amy appear a lot of times but have very little importance. thus we need to weight down the 
#frequent terms while scale up the rare ones, by computing the following:

#IDF(t) = Log_e(Total no of documents/No of documents in which term 't' appeared).


#consider a document containing 100 words wherein the word cat appeared 3 times
#we have total 10M documents the word cat appears in 1000 of times.

# tf = 3/100 = 0.3
#idf = log(10**7/10**3) = log(10**4) = 4
#TF-IDF = 0.3*4 = 0.12

In [16]:
# if in a given doument a term is occuring very frequently-----TF will be high.
# if a term is rarely occuring in a document then numerator will be low but idf will be high.

#conclusion: if a term ocuurs frequently in a given document but its a rarely occuring in other documents.
#TF-IDF weight of that term for given document will be large

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [18]:
tf = TfidfVectorizer()

In [19]:
tx = tf.fit(text)

In [20]:
#tx.vocabulary_

In [21]:
ty = tf.transform(text)

In [22]:
ty.shape   #5 documents and 87 unique tokens

(5, 87)

In [23]:
ty.toarray()[0]

array([0.17299624, 0.        , 0.        , 0.17299624, 0.17299624,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.17299624, 0.        , 0.17299624, 0.        ,
       0.        , 0.        , 0.17299624, 0.        , 0.        ,
       0.        , 0.17299624, 0.        , 0.        , 0.        ,
       0.17299624, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.09746307, 0.17299624, 0.        ,
       0.        , 0.17299624, 0.        , 0.17299624, 0.        ,
       0.13957228, 0.17299624, 0.3475728 , 0.13957228, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.17299624,
       0.        , 0.        , 0.17299624, 0.        , 0.        ,
       0.        , 0.17299624, 0.        , 0.        , 0.        ,
       0.        , 0.17299624, 0.        , 0.1158576 , 0.1158576 ,
       0.        , 0.17299624, 0.        , 0.16486727, 0.13957

# **Feature Scaling**

In [24]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import RobustScaler, MinMaxScaler, StandardScaler

In [25]:
#StandardScaler follows Standard Normal/Gaussian Distribution. Therefore, it makes mean = 0 and scales the data to unit variance.

In [26]:
#Since, it doesn't restict the data to a particular range.
#therefore it cannot guarantee balanced feature scales in the presence of outliers.

In [27]:
#MinMaxScaler scales all the data features in the range [0, 1] or else in the range [-1, 1]
#Unlike, StandardScaler it handles outliers.

In [28]:
#By using RobustScaler, we can remove the outliers and then use either StandardScaler or MinMaxScaler for preprocessing the dataset.

# **RobustScaler**

In [29]:
df = pd.DataFrame({'x1': np.concatenate([np.random.normal(20, 2, 1000), np.random.normal(1, 2, 25)]), 
    'x2':np.concatenate([np.random.normal(30, 2, 1000), np.random.normal(50, 2, 25)])})
df.head()

x1         x2
0  15.177038  31.431401
1  19.830563  29.177474
2  20.379101  31.144580
3  17.002280  29.985288
4  19.477615  32.672440

In [30]:
Rs = RobustScaler()
Rs.fit_transform(df)

array([[-1.72590728,  0.48747635],
       [-0.07020237, -0.31927383],
       [ 0.12496515,  0.38481427],
       ...,
       [-6.54596762,  5.56920867],
       [-7.27537831,  7.36956941],
       [-7.41544129,  6.79168559]])

# **StandardScaler**

In [31]:
Ss = StandardScaler()
Ss.fit_transform(df)

array([[-1.26171036,  0.2483523 ],
       [ 0.07747622, -0.35381245],
       [ 0.23533389,  0.17172451],
       ...,
       [-5.16032786,  4.04139775],
       [-5.75029832,  5.38520133],
       [-5.8635857 ,  4.95386425]])

# **MinMaxScaler**

In [32]:
mm = MinMaxScaler()
mm.fit_transform(df)

array([[0.59048105, 0.23255756],
       [0.76158897, 0.1607114 ],
       [0.78175846, 0.22341486],
       ...,
       [0.09235451, 0.68511772],
       [0.01697396, 0.84545114],
       [0.00249923, 0.79398696]])