In [9]:
a=[1,2]
b=[3,4]
c=a*b
c

TypeError: can't multiply sequence by non-int of type 'list'

In [ ]:
multiplication operation can't be applied on list elements
hence, we go for numpy array.

In [3]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[3,4],[5,6]])
a*b

array([[ 3,  8],
       [15, 24]])

In [ ]:
1.Numpy is a general-purpose array processing pkg.
2.Array in Numpy is a table containing elements, all of the same type(usually numbers), indexed by a touple of non-negative integers.
   a) Note:Type of array can be explicitly defined while creating the array.
   b) The type of resultant array is deduced from the type of the elements in the sequences.
3. In Numpy, no of dimensions of the array is known as rank of array.

# Array creation

In [35]:
                                        #from list
#array with rank1 
a=np.array([1,2,3,4])
print(a,'\n')

#array with rank2 
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[1 2 3 4] 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
                                    #matrix
m=np.matrix('1 2 3;4 5 6;7 8 9')
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
                                    #zeros, ones, eye
print(np.zeros((3,4)),'\n\n')
print(np.ones((4,3)),'\n\n')
print(np.eye((4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
####################################################   1-d array
#arange(start_value,end_value,step_size)
#default s_value=0, step_size=1

a=np.arange(7)
b=np.arange(0,6,3)
c=np.arange(1,7,0.5)
print("with default step size: ",a)
print("with step size 3: ",b)
print("with step size 0.5: ",c)
    

with default step size:  [0 1 2 3 4 5 6]
with step size 3:  [0 3]
with step size 0.5:  [1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5]


In [47]:
######################################################   1-d array
#linspace(s_value,e_value,no of elements)   
#it creates arrays with specific no of elements, which are equally spaced b/w begining and end value.
e=np.linspace(2,8,5)
e

array([2. , 3.5, 5. , 6.5, 8. ])

In [53]:
######################################################    1-d array
#randint(s_value,e_value,no of elements)

from numpy.random import randint as rd

f=rd(2,8,5)
print(f)

#by default no of elements is 1

g=rd(45,90)
print(g)

h=rd(1,100,10)
print(h)

[7 5 2 5 2]
87
[16 74 50 70 44 73 98 24 24 59]


In [49]:
#numpy.random.rand()
from numpy.random import rand as rn

x=rn(5)
y=rn(2,3)
z=rn(3,4,2)
print("randomly constructing 1d array with 5 elements: ",x)
print('randomly const 2d array with 2 rows nd 3 columns: ',y)
print('randomly constructing 3d array: with dimensions(3,4,2): ',z)

randomly constructing 1d array with 5 elements:  [0.00393342 0.35124434 0.11398232 0.33598378 0.56786599]
randomly const 2d array with 2 rows nd 3 columns:  [[0.30655928 0.6568331  0.87332613]
 [0.82947114 0.76904636 0.35050827]]
randomly constructing 3d array: with dimensions(3,4,2):  [[[0.51882925 0.35505721]
  [0.71322146 0.14411096]
  [0.63605416 0.57562686]
  [0.15514393 0.36627687]]

 [[0.95711312 0.93568677]
  [0.60090266 0.61689717]
  [0.97149823 0.20427201]
  [0.84169337 0.55347525]]

 [[0.56256736 0.59327836]
  [0.0228753  0.07894151]
  [0.02988173 0.82982151]
  [0.68212133 0.12145929]]]
