# Data Types in Numpy

In [2]:
#at the time of array creation, datatypes of array need not to be defined unless a specific datatype is required.
#but function that construct array usually also include an optional arg to explicitly specify the datatype.
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([1,-2.3])
print(a.dtype)
print(b.dtype)
c=np.array([[1,2,3],[4,5,6],[7,8,9]],dtype='float')
print('array created :',c)
print('data type :',c.dtype)

int64
float64
array created : [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
data type : float64


# math operations

In [10]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,6,5],[7,8,9],[1,6,4]])
c=np.matrix('9 7 3;2 3 6;1 5 9')

# 1. urnary operations

In [11]:
print('transpose of matrix :',a.T)
print('conjugate transpose of matrix :',c.H)

transpose of matrix : [[1 4 7]
 [2 5 8]
 [3 6 9]]
conjugate transpose of matrix : [[9 2 1]
 [7 3 5]
 [3 6 9]]


In [4]:
print("adding 2 to every element :",a+2)
print('sub 1 from evey element :',b-1)
print('multiply every element by 2 :',b*2)
print('square each element :',b**2)
s1=a.sum()
s2=a.sum(axis=0)
s3=a.sum(axis=1)
print("sum of all the elements :",s1,', sum of elelments column wise :',s2,', sum of elements row wise :',s3)
print("std deviation: ",a.std())

from numpy import exp,sqrt,sin
print('exp of every element: ',exp(a))
print('sqrt of every element: ',sqrt(a))
print('sine of every element: ',sin(a))

adding 2 to every element : [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
sub 1 from evey element : [[3 5 4]
 [6 7 8]
 [0 5 3]]
multiply every element by 2 : [[ 8 12 10]
 [14 16 18]
 [ 2 12  8]]
square each element : [[16 36 25]
 [49 64 81]
 [ 1 36 16]]
sum of all the elements : 45 , sum of elelments column wise : [12 15 18] , sum of elements row wise : [ 6 15 24]
std deviation:  2.581988897471611
exp of every element:  [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
sqrt of every element:  [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]
sine of every element:  [[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


# 2. binary operations

In [5]:
print('addition: ',a+b)
print('substraction: ',a-b)
print('array multiplication:',a*b)
print('matrix multiplication: ',a.dot(b))

addition:  [[ 5  8  8]
 [11 13 15]
 [ 8 14 13]]
substraction:  [[-3 -4 -2]
 [-3 -3 -3]
 [ 6  2  5]]
array multiplication: [[ 4 12 15]
 [28 40 54]
 [ 7 48 36]]
matrix multiplication:  [[ 21  40  35]
 [ 57 100  89]
 [ 93 160 143]]


# some basic operations

In [16]:
#reshape(n,m)
#n*m must be same as total no of elements in the array
print(np.random.randint(1,38,8).reshape(2,4))

[[19 36 20 26]
 [16 23 11 32]]


In [17]:
#flatten
print(np.random.rand(3,4).flatten())

[0.42919443 0.7507036  0.5927713  0.6481249  0.59233281 0.55195411
 0.18041372 0.02346107 0.75962035 0.02073814 0.98190453 0.17729369]


In [20]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("largest element in the array: ",a.max())
print("smallest element in the array: ",a.min())
print("index loc of maxi element: ",a.argmax())
print("index loc of mini element: ",a.argmin())

largest element in the array:  9
smallest element in the array:  1
index loc of maxi element:  8
index loc of mini element:  0


In [24]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,5,6]])

print("array type: ",type(arr))
print("no of dimensions of array: ",arr.ndim)#1D, 2D, 3D
print('size of array: ',arr.size)
print('shape of array: ',arr.shape)

array type:  <class 'numpy.ndarray'>
no of dimensions of array:  2
size of array:  12
shape of array:  (4, 3)


# map

In [27]:
arr=list(map(int,input().split()))
arr

1 2 3 4 5


[1, 2, 3, 4, 5]