In [1]:
import numpy as np

In [2]:
a=np.arange(1,11,1)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
print(a[0:-6])#1st element to 6th elemet from last
print(a[::-1])#rev array

[1 2 3 4]
[10  9  8  7  6  5  4  3  2  1]


In [8]:
b=a[:5]
print('sliced array: ',b)

sliced array:  [1 2 3 4 5]


In [11]:
b[:]=66
print(b)
print(a)

[66 66 66 66 66]
[66 66 66 66 66  6  7  8  9 10]


In [13]:
#this is because by default numpy creates reference to original array instead of copying
#if we want a copy we have to specify explicitly

arr_cpy=a[4:].copy()
arr_cpy

array([66,  6,  7,  8,  9, 10])

In [14]:
arr_cpy[:]=55
print(arr_cpy)
print(a)

[55 55 55 55 55 55]
[66 66 66 66 66  6  7  8  9 10]


# 2d array

In [16]:
x=np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [18]:
#accessing a particular element
print(x[2][1])
print(x[2,1])
#2nd mtd is preffered over 1st as it is less prone to error

7
7


In [23]:
#lets print (0th and 1st row) and (1st onwards cols)

print(x[:2][1:],'\n')#wrong o/p
print(x[:2,1:]) #correct o/p

[[3 4 5]] 

[[1 2]
 [4 5]]


In [31]:
#arr[row_index,column_index]
#row_index is mandatory
#col_index is optional

print(x[:2,:],'\n')
print(x[:2],'\n')
print('2nd row only',x[1])
print('2nd col only',x[:,1])

[[0 1 2]
 [3 4 5]] 

[[0 1 2]
 [3 4 5]] 

2nd row only [3 4 5]
2nd col only [1 4 7]


In [32]:
#printing indices at particular indices(1,0) (1,2) (0,1) (2,0)

print(x[[1,1,0,2],[0,2,1,0]])

[3 5 1 6]


In [33]:
x>2

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [33]:
(x>2)*1

array([[0,   0,  0],
       [ 1,  1,  1],
       [ 1,  1,  1]])

In [34]:
#x[#condition]
x[x>2]


array([3, 4, 5, 6, 7, 8])

In [36]:
#even no
print(x[x%2==0])
#odd no
print(x[x%2!=0])

[0 2 4 6 8]
[1 3 5 7]
