In [1]:
import numpy as np

In [2]:
a = np.array([[1,0,3],[4,6,1],[3,7,2]])
b = np.array([[2,9,5],[6,3,1],[7,9,2]])

**np.multiply(a,b)**

In [3]:
#Element-wise multiplication, or Hadamard Product
print(a*b)
print(np.multiply(a,b))

[[ 2  0 15]
 [24 18  1]
 [21 63  4]]
[[ 2  0 15]
 [24 18  1]
 [21 63  4]]


**np.dot(a, b)**

In [4]:
#Performs the dot product for 1-D arrays.
#Performs the matrix multiplication for 2-D arrays.
#For higher-dimensional arrays, it flattens the arrays to 1-D and
#then computes the dot product (not recommended for tensors).

In [5]:
## Dot product for 1-D arrays
np.dot([1,2,3],[4,5,6])  ## Output: 32 (1*4 + 2*5 + 3*6)

32

In [6]:
## Matrix multiplication for 2-D arrays
np.dot(a,b)

array([[23, 36, 11],
       [51, 63, 28],
       [62, 66, 26]])

**np.matmul(a, b)**

In [7]:
#Always performs matrix multiplication for 2-D arrays.
#For 1-D arrays, it treats them as row or column vectors (based on the context)
#to ensure correct matrix multiplication behavior.
#Supports broadcasting for higher-dimensional arrays, enabling batch matrix multiplication.

In [8]:
# Matrix multiplication for 2-D arrays (same as np.dot in this case)
np.matmul(a,b)

array([[23, 36, 11],
       [51, 63, 28],
       [62, 66, 26]])

In [9]:
## Matrix multiplication for 1-D arrays
np.matmul([1,2,3],[4,5,6])
#[1,2,3] x [[4]      [1 x 3] X [3 x 1] = [1 x 1]
#          [5]
#          [6]]

32

**np.cross(a,b)**

In [10]:
#The cross product is an operation that is defined only for 3-dimensional vectors.
#for matrices the cross product is computed row-wise.

In [11]:
#cross product of 1-D array
np.cross([1,2,3],[9,8,7])

array([-10,  20, -10])

In [12]:
#cross product of 2x3 matrix
np.cross([[1,2,3],[3,2,5]],[[9,8,7],[9,5,2]])

array([[-10,  20, -10],
       [-21,  39,  -3]])

In [13]:
#cross product of 2x3 matrix
mat_a = [[1, 2, 3], [3,2,5], [7, 9, 1]]
mat_b = [[9, 8, 7], [9,5,2], [3, 1, 1]]
np.cross(mat_a, mat_b)

array([[-10,  20, -10],
       [-21,  39,  -3],
       [  8,  -4, -20]])